---
abstract: 'A searchable store backed by Solr'
author:
  - 'Patrick Hochstenbach <patrick.hochstenbach@ugent.be>'
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Store-Solr
provides:
  Catmandu::Store::Solr:
    file: lib/Catmandu/Store/Solr.pm
    version: 0.0204
  Catmandu::Store::Solr::Bag:
    file: lib/Catmandu/Store/Solr/Bag.pm
  Catmandu::Store::Solr::CQL:
    file: lib/Catmandu/Store/Solr/CQL.pm
  Catmandu::Store::Solr::Searcher:
    file: lib/Catmandu/Store/Solr/Searcher.pm
requires:
  CQL::Parser: 1.12
  Catmandu: 0.7
  Moo: 1.00
  WebService::Solr: 0.16
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.0204
